# ============================================================
# OpenPaint pnpm Workspace
# ============================================================

packages:
  - 'src-web'
  - 'src-tauri/bin/plugins/*'

# 禁止提升未声明依赖，避免幽灵依赖
hoistPattern:
  - '*types*'
  - '*eslint*'
  - '*prettier*'
  - '@vue/*'